output: "result.mp4"
video:
  meta:
    width: 1920
    height: 1080
    bitrate: "1500k"
    fps: 25
  clips:
    - uid: 'video-clip-1'
      path: "example/bg.mp4"
      span: ["00:00:00.000", "00:00:10.000"]
    - uid: 'video-clip-2'
      path: "example/bg.mp4"
      span: ["00:00:10.000", "00:00:15.000"]
    - uid: 'video-clip-3'
      path: "example/fg.alpha.mov"
      layer: 1
      posX: 50
      posY: 50
      width: 240
      height: 360
      span: ["00:00:02.000", "00:00:08.000"]
    - uid: 'video-clip-4'
      path: "example/fg.mp4"
      layer: 1
      posX: 100
      posY: 100
      width: 480
      height: 720
      span: ["00:00:09.000", "00:00:12.000"]
audio:
  meta:
    sample_rate: 16000
  clips:
    - uid: 'audio-clip-1'
      path: "example/audio.wav"
      span: ["00:00:04.000", "00:00:06.000"]
      clip: ["00:00:00.000", "00:00:02.000"]
    - uid: 'audio-clip-2'
      path: "example/audio.wav"
      span: ["00:00:01.000", "00:00:03.000"]
      clip: ["00:00:00.000", "00:00:02.000"]
    - uid: 'audio-clip-3'
      path: "example/audio.wav"
      span: ["00:00:11.000", "00:00:14.000"]
      clip: ["00:00:00.000", "00:00:02.000"]
      loop: true
      volume: 2
      channel: 1
    - uid: 'audio-clip-4'
      path: "example/audio.wav"
      span: ["00:00:08.000", "00:00:11.000"]
      clip: ["00:00:00.000", "00:00:03.000"]
      channel: 2

subtitle:
  clips:
    - uid: 'subtitle-clip-1'
      text: "Clip 1 test"
      fontsize: 24
      primary_colour: "&H00FF0000"
      span: ["00:00:00.000", "00:00:02.000"]
    - uid: 'subtitle-clip-2'
      text: "Clip 2 test"
      fontsize: 28
      primary_colour: "&H0000FF00"
      span: ["00:00:02.000", "00:00:04.000"]
    - uid: 'subtitle-clip-3'
      text: "Clip 3 test"
      fontsize: 12
      primary_colour: "&H000000FF"
      span: ["00:00:04.000", "00:00:06.000"]

